version: 2.1
executors:
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
      NUGET_XMLDOC_MODE: skip
      CIRCLE_TEST_REPORTS: /workspace/circleci-test-results
  go:
    docker:
      - image: circleci/golang
jobs:
  build-test:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet tool install -g dotnet-reportgenerator-globaltool
      - run: dotnet build -c Debug
      - run: dotnet test -c Debug -p:CollectCoverage=true -p:CoverletOutputFormat=opencover --test-adapter-path:. --logger:"xunit;LogFilePath=results.xml" < /dev/null
      - run: curl -s https://codecov.io/bash > codecov
      - run: chmod +x codecov
      - run: ./codecov -f ./src/KustomizeConfigMapGenerator.Tests/coverage.opencover.xml
      - run:
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS
            echo 'export PATH=$PATH:$HOME/.dotnet/tools' >> $BASH_ENV
            source $BASH_ENV && dotnet tool install -g dotnet-xunit-to-junit
            dotnet-xunit-to-junit ./src/KustomizeConfigMapGenerator.Tests/results.xml "${CIRCLE_TEST_REPORTS}/results.xml"
      - store_test_results:
          path: /workspace/circleci-test-results
  build-push:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet build -c Release -p:Version=${CIRCLE_TAG}
      - run: dotnet test -c Release < /dev/null
      # KustomizeConfigMapGenerator
      - run: dotnet pack ./src/KustomizeConfigMapGenerator/KustomizeConfigMapGenerator.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
      - run: dotnet nuget push ./src/KustomizeConfigMapGenerator/bin/Release/KustomizeConfigMapGenerator.${CIRCLE_TAG}.nupkg -s https://www.nuget.org/api/v2/package -k ${NUGET_KEY}
      - store_artifacts:
          path: ./src/KustomizeConfigMapGenerator/bin/Release
          destination: ./KustomizeConfigMapGenerator/
      # dotnet-kustomizationconfigmapgenerator-project-tool
      - run: dotnet pack ./src/dotnet-kustomizationconfigmapgenerator-project-tool/dotnet-kustomizationconfigmapgenerator-project-tool.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
      - run: dotnet nuget push ./src/dotnet-kustomizationconfigmapgenerator-project-tool/bin/Release/dotnet-kustomizationconfigmapgenerator-project-tool.${CIRCLE_TAG}.nupkg -s https://www.nuget.org/api/v2/package -k ${NUGET_KEY}
      - store_artifacts:
          path: ./src/dotnet-kustomizationconfigmapgenerator-project-tool/bin/Release
          destination: ./dotnet-kustomizationconfigmapgenerator-project-tool/
  build-singlepackage:
    executor: dotnet
    steps:
      - checkout
      # KustomizeConfigMapGenerator
      - run: dotnet publish ./src/KustomizeConfigMapGenerator/ -c Release -o ./KustomizeConfigMapGenerator -r win-x64 -p:PublishSingleFile=true -p:Version=${CIRCLE_TAG}
      - run: dotnet publish ./src/KustomizeConfigMapGenerator/ -c Release -o ./KustomizeConfigMapGenerator -r linux-x64 -p:PublishSingleFile=true -p:Version=${CIRCLE_TAG}
      - run: dotnet publish ./src/KustomizeConfigMapGenerator/ -c Release -o ./KustomizeConfigMapGenerator -r osx-x64 -p:PublishSingleFile=true -p:Version=${CIRCLE_TAG}
      - persist_to_workspace:
          root: .
          paths:
            - ./KustomizeConfigMapGenerator
  upload-github:
    executor: go
    steps:
      - attach_workspace:
          at: ./artifacts
      - run: go get github.com/tcnksm/ghr
      - run: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -delete ${CIRCLE_TAG} ./artifacts/KustomizeConfigMapGenerator/
      - store_artifacts:
          path: ./artifacts/KustomizeConfigMapGenerator
workflows:
  build-and-push:
    jobs:
      - build-test:
          filters:
            tags:
              only: /.*/
      - build-push:
          context: nuget
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - build-singlepackage:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - upload-github:
          requires:
            - build-singlepackage
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
