name: dotnet-build

# run on both branch push and tag push
on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  dotnet:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.x
      - run: dotnet build ./src/KustomizeConfigMapGenerator/ -c Debug
      - run: dotnet build ./src/dotnet-kustomizationconfigmapgenerator-project-tool/ -c Debug
      - run: dotnet test ./src/KustomizeConfigMapGenerator.Tests/ -c Debug -p:CollectCoverage=true -p:CoverletOutputFormat=opencover --test-adapter-path:. --logger:"xunit;LogFilePath=results.xml"
      - uses: codecov/codecov-action@v1
        with:
          file: ./src/KustomizeConfigMapGenerator.Tests/coverage.opencover.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
